accessibility design
ruby-no-kai/official pull request #278
Opened 2017-05-29 03:01 UTC by shyouhei

related #268 

@ruby-no-kai/rk17-orgz CC @shioyama Please check.

2017-05-29 12:21 UTC, takahashim commented on policies/rubykaigi2017/accessibility-policy-ja.md
> +私たちはカンファレンスがすべての参加者を等しく歓迎し、招き入れ、そして利用しやすいものになるように専念してきました。いくらかの取り組みに関しては、カンファレンスの物理的な設計や運用に組み込んできています:
「物理的な」はなくてもよいかも？

2017-05-29 12:21 UTC, takahashim commented on policies/rubykaigi2017/accessibility-policy-ja.md
> +しかしながら、同時に、アクセシビリティの問題はこれだけに限らず、さまざまであることも認識しているところです。アクセシビリティに関して上記以外の考慮事項を必要とされる方、またご意見やご質問のある方は、どうぞ、ご遠慮なく[オーガナイザーにご連絡](mailto:info@rubykaigi.org)ください。残念ながらすべてのご要望に必ずお応えできるとお約束することは困難ですが、それぞれの事情をうか
連絡先は info@rubykaigi.org ではなく 2017@rubykaigi.org にしたほうがよさそうです。

2017-05-29 12:28 UTC, shioyama commented on policies/rubykaigi2017/accessibility-policy-en.md
> +  - We offer significantly discounted tickers as well as admission free day for students.
"tickers" -> "tickets"

2017-05-29 12:29 UTC, shioyama commented on policies/rubykaigi2017/accessibility-policy-en.md
> +  - We offer significantly discounted tickers as well as admission free day for students.
"as well as admission free day" ->
"as well as an admission free day"

2017-05-29 12:29 UTC, shioyama commented on policies/rubykaigi2017/accessibility-policy-en.md
> +  - We provide invitation letters to whom need to obtain a visa in order to visit Japan.
"to whom need to obtain" ->
"to those who need to obtain"

2017-05-29 12:31 UTC, shioyama commented on policies/rubykaigi2017/accessibility-policy-en.md
> +However, the organizers also recognize that accessibility issues are diverse. If you have any other accessibility requirements, or if you have any other feedback or questions, then please don’t hesit
This is not grammatically wrong, but I would reword the last sentence a bit:

"While we can't promise the ability to accommodate each individual situation, we absolutely commit to listening to..." ->
"Whiel we cannot promise to accommodate each individual situation, we are committed to listening to..."

2017-05-29 12:32 UTC, shioyama requested changes
いくつかの小さい修正が必要

2017-05-30 01:49 UTC, shyouhei commented on policies/rubykaigi2017/accessibility-policy-en.md
> +However, the organizers also recognize that accessibility issues are diverse. If you have any other accessibility requirements, or if you have any other feedback or questions, then please don’t hesit
OK, no objection.

2017-05-30 01:49 UTC, shyouhei commented on policies/rubykaigi2017/accessibility-policy-ja.md
> +しかしながら、同時に、アクセシビリティの問題はこれだけに限らず、さまざまであることも認識しているところです。アクセシビリティに関して上記以外の考慮事項を必要とされる方、またご意見やご質問のある方は、どうぞ、ご遠慮なく[オーガナイザーにご連絡](mailto:info@rubykaigi.org)ください。残念ながらすべてのご要望に必ずお応えできるとお約束することは困難ですが、それぞれの事情をうか
はい…そこは相談したいところ。恒久的なアドレスがあってもよいかもとは思います

2017-05-30 01:51 UTC, shioyama commented
The original English on this was very good btw. My corrections are mostly minor :smile:

2017-05-30 02:06 UTC, shyouhei commented
@shioyama Thank you!  Will update the pointed parts.

2017-05-30 03:53 UTC, shyouhei commented on policies/rubykaigi2017/accessibility-policy-ja.md
> +私たちはカンファレンスがすべての参加者を等しく歓迎し、招き入れ、そして利用しやすいものになるように専念してきました。いくらかの取り組みに関しては、カンファレンスの物理的な設計や運用に組み込んできています:
どうでしょう、それは英語版に書いてあるphysical designの訳のつもりなんですが、physical designを物理的な設計という言葉にするのが間違っているかもしれない。すごく冗長にいうと、建物とかのアレンジメントも含めた、物の配置などの考え方のことだと思うのですが。なんていえばいいのかな。

2017-06-05 02:50 UTC, shyouhei commented
@shioyama can you have a look at it again?

2017-06-07 12:41 UTC, amatsuda commented on policies/rubykaigi2017/accessibility-policy-ja.md
> +しかしながら、同時に、アクセシビリティの問題はこれだけに限らず、さまざまであることも認識しているところです。アクセシビリティに関して上記以外の考慮事項を必要とされる方、またご意見やご質問のある方は、どうぞ、ご遠慮なく[オーガナイザーにご連絡](mailto:info@rubykaigi.org)ください。残念ながらすべてのご要望に必ずお応えできるとお約束することは困難ですが、それぞれの事情をうか
僕はどちらかと言えば 2017@ に一票です。毎年やるとは現時点で断言はできなくて、とりあえず今年はやってみる、ぐらいの気持ちです。

2017-06-08 04:55 UTC, takahashim approved these changes

2017-06-14 11:05 UTC, shyouhei commented
Let me merge.

2017-06-14 11:05 UTC, merged